prometheus:
  url: http://prometheus.monitoring.svc
  port: 9090
  path: ""

rules:
  default: false
  custom:
    - seriesQuery: 'http_request_duration_seconds_count{namespace!="",handler="/generate",method="POST"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: "^http_request_duration_seconds_count$"
        as: "genai_api_latency_avg_seconds"
      metricsQuery: >
        (
          sum(
            rate(http_request_duration_seconds_sum{<<.LabelMatchers>>,handler="/generate",method="POST"}[2m])
          ) by (namespace)
        )
        /
        (
          sum(
            rate(http_request_duration_seconds_count{<<.LabelMatchers>>,handler="/generate",method="POST"}[2m])
          ) by (namespace)
        )
