namespace:
  create: false

llm:
  model: tinyllama
  persistence:
    size: 8Gi

api:
  logLevel: DEBUG
  replicaCount: 5

ui:
  service:
    type: NodePort
    nodePort: 30081

ingress:
  enabled: false
